# **Scrapping Google Play Review Jenius App**

Pada tahap pengumpulan data, digunakan teknik web scrapping pada platform Google Play Store dengan target aplikasi perbankan digital Jenius. Ekstraksi ulasan pengguna dilakukan menggunakan library **`google-play-scraper`** dengan memanfaatkan fungsi **`reviews_all`** yang memungkinkan pengambilan data secara menyeluruh tanpa batasan jumlah. Konfigurasi scraping diarahkan pada identifikasi paket aplikasi **`com.btpn.dc`** dengan parameter bahasa ditetapkan pada Bahasa Indonesia (**`'id'`**) guna memfokuskan perolehan data pada ulasan berbahasa Indonesia. Keseluruhan ulasan yang tersedia diambil menggunakan metode pengurutan berdasarkan ulasan terbaru **`(Sort.NEWEST)`** untuk menjamin relevansi dataset dengan kondisi aktual aplikasi pada saat penelitian dilakukan. Tahapan ini berfungsi sebagai fondasi pembangunan dataset primer yang akan menjadi bahan analisis pada proses selanjutnya.

## Instalasi Library

In [6]:
!pip install google_play_scraper
!pip install PySastrawi

Requirement already satisfied: google_play_scraper in /usr/local/lib/python3.12/dist-packages (1.2.7)
Collecting PySastrawi
  Downloading PySastrawi-1.2.0-py2.py3-none-any.whl.metadata (892 bytes)
Downloading PySastrawi-1.2.0-py2.py3-none-any.whl (210 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.6/210.6 kB 2.8 MB/s eta 0:00:00
Installing collected packages: PySastrawi
Successfully installed PySastrawi-1.2.0

In [8]:
from google_play_scraper import app, reviews_all, Sort
from datetime import datetime
import pandas as pd
import numpy as np

## Detail Information Jenius App

In [9]:
# 1. Mengambil detail aplikasi menggunakan App ID Jenius
result = app(
    'com.btpn.dc',
    lang='id',
    country='id'
)

# 2. Konversi Timestamp ke Format Tanggal Manusia
dt_object = datetime.fromtimestamp(result['updated'])
tanggal = dt_object.strftime('%d %B %Y, %H:%M WIB')

# 3. Menampilkan informasi spesifik terkait update
print(f"Nama Aplikasi     : {result['title']}")
print(f"Versi Terbaru     : {result['version']}")
print(f"Terakhir Diupdate  : {tanggal}")

# 4. Menampilkan dalam bentuk DataFrame
df_detail = pd.DataFrame([result])
df_detail['updated_formatted'] = tanggal
display(df_detail[['title', 'version', 'updated_formatted', 'installs']])

Nama Aplikasi     : Jenius
Versi Terbaru     : 4.66.1
Terakhir Diupdate  : 18 March 2026, 03:20 WIB

    title version         updated_formatted     installs
0  Jenius  4.66.1  18 March 2026, 03:20 WIB  10.000.000+

##Scrapping Jenius App Review

In [11]:
# 1. Proses scrap
jenius_reviews_id = reviews_all(
    'com.btpn.dc',
    sleep_milliseconds=0,
    lang='id',
    country='id',
    sort=Sort.NEWEST,
)

print(f'✅ Scraping selesai! Total ulasan terkumpul: {len(jenius_reviews_id):,}')

# 2. Menyimpan ke DataFrame
df_jenius_id = pd.DataFrame(np.array(jenius_reviews_id), columns=['content'])
df_jenius_id = df_jenius_id.join(pd.DataFrame(df_jenius_id.pop('content').tolist()))

print(f'\nJumlah baris  : {df_jenius_id.shape[0]:,}')
print(f'Jumlah kolom  : {df_jenius_id.shape[1]}')

df_jenius_id.head()

# 3. Simpan ke file csv
output_path = "rawdata_jenius_id.csv"
df_jenius_id.to_csv(output_path, index=False, encoding="utf-8")
print(f'\n✅ Data berhasil disimpan ke: {output_path}')

✅ Scraping selesai! Total ulasan terkumpul: 101,151

Jumlah baris  : 101,151
Jumlah kolom  : 11

✅ Data berhasil disimpan ke: rawdata_jenius_id.csv

In [13]:
display(pd.concat([df_jenius_id.head(), df_jenius_id.tail()]))

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,c4fff659-dc8d-4449-92bd-c31e47cce376,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"payah udah cape"" isi data , login suruh isi da...",1,0,4.66.1,2026-03-23 09:31:49,Mohon maaf atas ketidaknyamanan yang kamu alam...,2026-03-23 09:32:47,4.66.1
1,cbfc7f4a-d5f6-48ef-a6f6-2a30ea8e159d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,mohon bantu saya tidak pernah mengajukan pinja...,1,0,4.66.1,2026-03-23 07:25:07,Hi Sarwedi Silalahi. Mohon maaf atas ketidakny...,2026-03-23 07:32:36,4.66.1
2,163b3f92-772b-41d5-9c89-2d083ed3a355,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,mobile banking paling berat dan lambat yang pe...,1,0,4.66.1,2026-03-22 23:24:37,Hi Kusnadi. Mohon maaf atas ketidaknyamanannya...,2026-03-22 23:31:12,4.66.1
3,b0eb2070-29d3-4f1d-b525-b2ecc70d0bda,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"tolong perbaiki sistemnya ya, kita sudah berus...",1,0,None,2026-03-22 13:33:56,Hai Andhy Hutomo. Terima kasih atas ulasan yan...,2026-03-22 13:35:34,None
4,e265485e-090f-4b1c-9a0b-6df7bdadebfd,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"saya ingin unlink device, tapi sangat sulit. s...",1,0,4.66.1,2026-03-22 11:17:12,Hi Kak. Mohon maaf atas ketidaknyamanan yang d...,2026-03-22 11:19:39,4.66.1
101146,d4774bcb-cd37-4794-aafc-71418f71b71a,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"ah bijimana aplikasi ini ?,,gw register proses...",1,19,1.0.0,2016-08-11 07:47:19,"Hi Nesken Sitangggang, terima kasih telah men-...",2016-08-13 15:54:29,1.0.0
101147,d2025bb4-9836-4868-8d0d-1d0317cda408,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Bagus,4,0,None,2016-08-11 07:12:12,"Thank you, Miftah Dewa\nLet's discover a new w...",2016-09-06 09:57:34,None
101148,b16f046a-0a3e-4f34-b68e-03cd8a51bcde,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Jenius abis,5,3,1.0.0,2016-08-11 06:45:11,"Thank you, Helve Krustiarnando\nLet's discover...",2016-09-06 09:55:44,1.0.0
101149,9298f6dd-4269-4d68-80ca-0ebc29190a60,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Ada error di bagian regist. Enggak tau apa cum...,3,12,1.0.0,2016-08-11 06:00:25,"Hi Syifa Chairannisa, terima kasih telah mengu...",2016-08-13 16:14:27,1.0.0
101150,f8ca8d1e-0773-4b9e-8d56-83caca4309ca,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi ini sangat menghemat waktu saya,5,3,None,2016-08-11 05:06:14,"Thank you, Denny Andianto.\nLet's discover a n...",2016-09-06 09:44:26,None